### ISSUE TITLE
Can't open ICS files with this app from Thunderbird on Android 14

### ISSUE THREAD

**Issue by skylarmt** [SufficientlySecure/calendar-import-export#109]
When I open an ICS file from Thunderbird/K-9 Mail, Calendar Import/Export is not in the "open with" app list.  Therefore, I have to save each ICS file (with a different name each time because otherwise Thunderbird puts ` (1)` after the `.ics` which prevents this app from finding the file), then open this app, have it search for ICS files, import the file, then manually delete it from the Files app.

What should happen is when I try to open an ICS file, this app is listed in the "open with" list.  This used to be the case on my old phone running an older version of Android.

**Comment by woheller69** [comment]
I have Android 14 and the app is in "open with" list...

**Comment by skylarmt** [comment]
I just realized it does work in some apps but not others.

**Comment by skylarmt** [comment]
The apps that show up when opening in Thunderbird are ones that support handling many file formats (such as Termux and a text editor).  Maybe some mime type isn't being done properly.

**Comment by woheller69** [comment]
Maybe an issue in Thunderbird?

**Comment by skylarmt** [comment]
Maybe.  It definitely used to work though, where this app was an option even where other calendar apps were not.  Was there a change at some point in how this app handles files associations or something?

**Comment by skylarmt** [comment]
Turns out the application that was emailing me calendar files was setting the wrong MIME type for the ICS attachments. I've opened a pull request to fix it there.
