### ISSUE TITLE
Release status

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/calendar-import-export#21]
Hey @jgriffiths
I prepared everything for a Google Play and F-Droid release. I also re-designed Offline Calender and tested the interoperability via the Intent and fixed it. I think everything is already good enough (tm) for a release. Many people have asked for a backup/restore feature for Offline Calender, so I would like to release ASAP.
We can rework the design of the UI in a later release.
Please also contact me via email, I can give you access to the Google Play dev console for this app.
Are you okay with this?

**Comment by jgriffiths** [comment]
Hi @dschuermann,

I'd be glad to see a release, although I wasn't expected to see one quite so soon. Can you give me 2-3 days to make some final tests/changes before releasing?

I will email you shortly.

**Comment by dschuermann** [comment]
@jgriffiths sure, take your time.

**Comment by Gitoffthelawn** [comment]
@jgriffiths As you test it, you may want to verify it works with exports from *Business Calendar* and *Business Calendar 2*.

You may also want to see if the icl files you generate work as imports into those apps.

**Comment by dschuermann** [comment]
There are many closed source apps handling ICS files. For now, I don't think we need to test them. I would concentrate on a fully functional export from our app that afterwards imports again without problems.

**Comment by jgriffiths** [comment]
@dschuermann, I think it should be OK to release when you are ready. I will continue making further changes, mostly around testing at first. I suspect this will be very useful when the first bug reports inevitably start rolling in.

My email is jon_p_griffiths <at_sign> yahoo <dot> com.

**Comment by jgriffiths** [comment]
@Gitoffthelawn In the true spirit of open source, I'm planning to let the users test the apps compatibility with other calendars :-)

In all seriousness though, I know for a fact that there will be bugs in both import and export for common calendar sources like Outlook and Google. I don't have the time to exhaustively test the apps I think users are likely to use. I think the smart thing to do is let the users raise the issues that are important to them and address those that are most common/most important (i.e. have the users triage the issues).

In the meantime I want to get the behaviour under test so we can release fixes quickly without fear of introducing regressions.

**Comment by dschuermann** [comment]
Released to Google Play and F-Droid (https://gitlab.com/fdroid/fdroiddata/merge_requests/976)
Could take some time until it is out.

**Comment by dschuermann** [comment]
@jgriffiths 

Oh yeah:
![ical_evil](https://cloud.githubusercontent.com/assets/321888/9849152/66c13a6e-5ae8-11e5-8c05-2a452995c54c.png)

**Comment by jgriffiths** [comment]
dschuermann haha! Thanks for the release mate!

**Comment by dschuermann** [comment]
@jgriffiths Thanks for your dedication. You are doing important work for the open source community!
