### ISSUE TITLE
Remove slash in app name

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/calendar-import-export#28]
From mailinglist:

>  Hi!
> Please remove the slash from the name of the application. The current name
is insurmountable for many applications that perform the backup.
In the case of Total Commander truncate the name.
File Expert 4.0.7 does not perform any backup of any applications.
Thanks

**Comment by jgriffiths** [comment]
@dschuermann I'll leave this to you. Its obviously a bug in the users backup app, the question is whether to bother working around it. You could always replace the '/' with '-' I suppose.

**Comment by Gitoffthelawn** [comment]
Is there a spec that shows valid characters for Android app names?  It's interesting that the mailinglist poster has multiple applications that cannot handle slashes... that implies it could be an illegal character... or perhaps all those apps just aren't escaping it properly.

**Comment by dschuermann** [comment]
I don't think that there is any spec for Android app names, but I would propose switching to "-". Did it here https://github.com/SufficientlySecure/calendar-import-export/commit/76dcd362493fa824a627b7fa28bbf3d90182c067

**Comment by dschuermann** [comment]
I released a new version...

**Comment by Gitoffthelawn** [comment]
Looks good.

**Comment by jgriffiths** [comment]
> Is there a spec that shows valid characters for Android app names? 

AFAICS, app names are free form text. The problem appears to be that backup apps use this name instead of the java package path when creating backups, and don't escape path special characters.
