### ISSUE TITLE
New icon 

### ISSUE THREAD

**Issue by halcyonest** [SufficientlySecure/calendar-import-export#31]
A sample of new icon for Calendar Import/Export.

![iconie](https://cloud.githubusercontent.com/assets/12594372/10501364/a27e9a56-731b-11e5-9124-633e58152df4.png)

*Download ![iconIE.svg.png](https://cloud.githubusercontent.com/assets/12594372/10501370/b0abb4e2-731b-11e5-9997-a6712fdc6088.png) and change '.png' extension into '.svg' to get an original SVG file.*

**Edit: Major modification was made to avoid plagiarism.**

**Released under CC BY-NC-SA**

**Comment by dschuermann** [comment]
Everything is designed by you and put into public domain?

**Comment by halcyonest** [comment]
Yes I made it and also please check 'Offline Calendar' project too, I made an icon for that too.

**Comment by dschuermann** [comment]
@halcyonest Great. I would love to see something similar to those with a birthday cake for https://github.com/SufficientlySecure/birthday-adapter . Can you do that?

**Comment by halcyonest** [comment]
![icon](https://cloud.githubusercontent.com/assets/12594372/10484436/00a1e86a-72c0-11e5-9ccf-635adecb33b8.png)

*Download ![icon.svg.png](https://cloud.githubusercontent.com/assets/12594372/10484446/0f767770-72c0-11e5-9ab3-1c9e90f36880.png) and remove '.png' extension to get an original SVG file.*

**Comment by Gitoffthelawn** [comment]
WOW!  Those are great icons!  Well done!  I like them so much I'm thinking of using them for my regular calendar app!

My only thought for improvement is the contrast between the gray top and the green bottom... there's something not-quite-aesthetically-pleasing there (for me).  It's like it is a monochrome and a color icon merged together, and seems just a touch unappealing.  Perhaps that feedback will encourage you to play with it more.

But besides that very minor nit, overall the icons you made are absolutely fantastic and beautiful.  I really like how you captured the idea of a calendar without having to put a big number on it like so many other designs.  You've done an amazing job conveying a complex notion - a scheduling calendar - in a visual manner.  Well done!

**Comment by halcyonest** [comment]
Sorry for the inconvenience, I recently got a mention that it looks similar to CyanogenMod's stock calendar app icon. Basically I got the ideo of this kind of design from an image website. I don't know the licence of his icon, so I'm trying to redesign it - into more 'agenda' type. Don't use this icon, please wait a little. Also about color scheme, Google Calendar app icon also uses grey top with blue square, so that's why I picked that.

**Comment by Gitoffthelawn** [comment]
I really liked the previous version more.  If you were unaware of any similar icons and created yours from scratch, it seems like that is okay.  But I'm (thankfully) not a lawyer.

**Comment by dschuermann** [comment]
Cyanogenmod's icon has been introduced here: https://github.com/CyanogenMod/android_packages_apps_Calendar/commit/dee6049d630b7bd816199dbd11aac9fc7cde5355 . It is licensed under Apache License v2, so no problem to do derivative work. I actually like both versions, but there should be no problem to go back and use the previous one in terms of license.

**Comment by halcyonest** [comment]
![iconba2](https://cloud.githubusercontent.com/assets/12594372/10511379/bf9bf8c4-7373-11e5-9218-9c55c58da6a4.png)

*Download ![iconBA2.svg.png](https://cloud.githubusercontent.com/assets/12594372/10511382/bfbea518-7373-11e5-84a5-813c023d8e8e.png) and remove '.png' extension to get an original SVG file.*

![iconie2](https://cloud.githubusercontent.com/assets/12594372/10511380/bfa627cc-7373-11e5-9b7a-0328deb431cb.png)

*Download ![iconie2 svg](https://cloud.githubusercontent.com/assets/12594372/10511381/bfa99e70-7373-11e5-8e3f-41323c5faa7f.png) and remove '.png' extension to get an original SVG file.*

**Released under Apache Licence 2.0**

**Comment by Gitoffthelawn** [comment]
@halcyonest Fantastic!

**Comment by dschuermann** [comment]
Icon has been merged here: https://github.com/SufficientlySecure/calendar-import-export/commit/3f3d61aa765149ab507c9b792953f49e8771a67c

**Comment by dschuermann** [comment]
And here: https://github.com/SufficientlySecure/birthday-adapter/commit/0dfb492d92d73d83c32684fe68668cf5713c80d0
