### ISSUE TITLE
Create default file names from the calendar name

### ISSUE THREAD

**Issue by Gitoffthelawn** [SufficientlySecure/calendar-import-export#38]
Create default file names from the calendar name.

For example, when backing up a calendar named 'Domonik's Calendar', use a default file name of `Domonik's Calendar'.

As an option, the file name can be appended with the current date/time.  But this should be an option, because it will prevent the previous backups from being overwritten, which will result in many files.  A "keep x backups for each calendar" option could be ideal.

**Comment by jgriffiths** [comment]
The app currently remembers the last name you used and fills the Filename dialog with it for you when you next export. My intention is that scheduled exports will work with their own complete copy of the current config and the scheduled save location will be available to edit.

I think defaulting the name on the dialog when its empty (on initial install), and having a 'suggest name' button on it would address this sufficiently.

**Comment by jgriffiths** [comment]
Note that the file name suggested is mangled to remove characters that may cause issues in file names.
