### ISSUE TITLE
Request: Add option to not export events with UUID's

### ISSUE THREAD

**Issue by Gitoffthelawn** [SufficientlySecure/calendar-import-export#46]
It appears there are some serious issues in Android with getting it to actually delete events for local calendars.

I have yet to find a single Android app that uses local calendars that can successfully delete events.  Yes, it appears the events are deleted, but they never actually get deleted.  When this app is used, all the supposedly deleted events get exported alongside the actual events.

If you know of a calendar app that uses local calendars, and can *actually* delete events, please post it here!

In order to work around this issue, some popular apps remove the UUID's of events that the user wants to delete.  Even though those events don't actually get deleted in the database, the apps know not to show those events in the calendar.

Can an option be added to this app to *not* export events that don't have UUID's?

**Comment by jgriffiths** [comment]
I can't reproduce this issue, and locally created events in the stock CM calendar do not have a UUID present in the database so this approach does not look like it will work. Also deleted calendars are not exported for me, so please continue discussions under issue #44 to determine what the actual problem is and how best to fix it in your case.

**Comment by Gitoffthelawn** [comment]
So strange.  What version of CM were you using?  Is it using Google's calendar app or a modified calendar app?  Is it able to delete/edit individual events in a series without assigning a UUID?

If you can, try installing this freeware app: https://play.google.com/store/apps/details?id=org.withouthat.acalendar

Once installed, use it to create a new local calendar.  Then, in that calendar, create two events.  Finally, delete the first one.  100% of the time when I do this simple test, *Calendar Import / Export* will export 2 events even though there is only 1.

**Comment by jgriffiths** [comment]
As discussed above, I'm not going to install other apps at this time. My Android version is 6.01, CM version 13.0.20160510-NIGHTLY-M8.

Please provide a debug log when you can, so I can look at the underlying cause of this issue.
