### ISSUE TITLE
[bug] Appointments over multiple day shrink to one day

### ISSUE THREAD

**Issue by mitras2** [SufficientlySecure/calendar-import-export#50]
This is the problem:
I exported an calendar with appointments that span over multiple days. Some of them have date+time for beginning and end. Others are define to be on from day x to y (complete day).
While the appointments with date+time stay spanned over multiple days, the other ones that are defined for the complete days are shrunk down to the first day.

Example:
LAN-Party
from 15.07.2016 10:00
to 17.07.2016 18:00

becomes:
BEGIN:VEVENT
...
SUMMARY:LAN-Party
ORGANIZER:mailto:me@owncloud.local
LOCATION:Somewhere
STATUS:CONFIRMED
DTSTART;TZID=Europe/Berlin:20160114T100000
DTEND:20160717T180000Z
END:VEVENT

4 days of Filming
from 25.07.2016
to 28.07.2016

becomes:
BEGIN:VEVENT
...
SUMMARY:4 days of Filming
ORGANIZER:mailto:me@owncloud.local
LOCATION:Somewhere
STATUS:CONFIRMED
DTSTART;VALUE=DATE:20160725
DTEND;VALUE=DATE:20160726
END:VEVENT

Version is 2.3
on Android 4.4.3

**Comment by mitras2** [comment]
I think the bug is in ProcessVEvent.java around line 249:
https://github.com/SufficientlySecure/calendar-import-export/blob/master/CalendarImportExport/src/main/java/org/sufficientlysecure/ical/ProcessVEvent.java#L249

The assumption that all-day-events always only span one day is wrong...

**Comment by mitras2** [comment]
OK - I have to correct my last message:
The error lies in SaveCalendar.java, line 333:
https://github.com/SufficientlySecure/calendar-import-export/blob/master/CalendarImportExport/src/main/java/org/sufficientlysecure/ical/SaveCalendar.java#L333

I forked the git-repo some night-hours ago and build a quick and dirty fix:

`            String endTz = Events.EVENT_END_TIMEZONE;
            if (endTz == null) {
                endTz = Events.EVENT_TIMEZONE;
            }
            Date dateEnd = getDateTime(cur, Events.DTEND, endTz, cal);

            if(dateEnd.getTime() % 86400000 == 0){
                dtEnd = new DtEnd(utcDateFromMs(dateEnd.getTime()));
            } else {
                dtEnd = new DtEnd(utcDateFromMs(start.getTime() + DateUtils.DAY_IN_MILLIS));
            }
            l.add(dtEnd);`
If I replace line 333 and 334 with that code i have a working solution for me BUT THIS MIGHT BE A BAD SOLUTION FOR OTHER CASES! So don't copy that code as a final bugfix (that's why I won't start a pull request with that code either...)

**Comment by mitras2** [comment]
After a few crashes and tests i just refined my code a bit. It's quite more to read, but it handles more (and some common) cases:

'''java
            String endTz = Events.EVENT_END_TIMEZONE;
            if (endTz == null) {
                endTz = Events.EVENT_TIMEZONE;
            }
            Date dateEnd = getDateTime(cur, Events.DTEND, endTz, cal);

            /*
            Log.d("mitras2_cal", "The 'all-day'-event is: "  + summary +".\n" +
                    "It's duration is: " + getString(cur, Events.DURATION) + ".\n" +
                    "StartDate is: " + start.toString() + " and the\n" +
                    "EndDate is: " + dateEnd.toString());
            */

            if(dateEnd == null || dateEnd.getTime() < start.getTime()+DateUtils.DAY_IN_MILLIS){
                // Error-Handling, for all-day-events that only run one day
                dtEnd = new DtEnd(utcDateFromMs(start.getTime() + DateUtils.DAY_IN_MILLIS));
            } else {
                if(dateEnd.getTime() % DateUtils.DAY_IN_MILLIS == 0){
                    dtEnd = new DtEnd(utcDateFromMs(dateEnd.getTime()));
                } else {
                    // If the events does not end exactly at the end of a day we fill the day up
                    // or we cut it, depending where the endDate was closer to

                    Long dateEndCorrection = 0L;
                    if(dateEnd.getTime() % DateUtils.DAY_IN_MILLIS >= (DateUtils.DAY_IN_MILLIS/2L)){
                        //If the dateEnd is beyond 12am  fill the day up till the next midnight
                        dateEndCorrection = (DateUtils.DAY_IN_MILLIS - (dateEnd.getTime() % DateUtils.DAY_IN_MILLIS));
                    } else {
                        //If the dateEnd is somewhere bevor 12am cut the day to its beginning
                        dateEndCorrection = (-dateEnd.getTime() % DateUtils.DAY_IN_MILLIS);
                    }
                    dtEnd = new DtEnd(utcDateFromMs(dateEnd.getTime() + dateEndCorrection));
                }
            }


            l.add(dtEnd);
'''

PS:
It replaces the same lines - 333 + 334

PPS:
This is still no perfect solution - but it's was better than the one before. Caution: At the moment I completely ignore "DURATION"...

**Comment by jgriffiths** [comment]
@mitras2 thanks for the great report. I'll try to look at this this weekend, no doubt some test cases will be needed.

**Comment by doak** [comment]
@jgriffiths: Did you gain any progress? The nasty bug which prevents this app to be used as an stable importer/exporter still exists :(

**Comment by jgriffiths** [comment]
Hi @doak unfortunately I have been very busy with work. I will try to take some time to look at recent reports this weekend.

**Comment by tasn** [comment]
Hey there,
Any updates on this one?
@doak, does your code work, or is it a hack? If it works, maybe consider creating a pull request?

Thanks,
Tom.

**Comment by mitras2** [comment]
@tasn So is this Problem fixed now?

**Comment by tasn** [comment]
It's fixed in my pull request (#64), though not yet merged.

**Comment by doak** [comment]
@tasn: Thank you very much! I am just waiting to get v2.5 available on F-Droid .. ;)

Regards,
doak

**Comment by tasn** [comment]
@doak, same here. At least it's available on Google Play for now.

**Comment by dschuermann** [comment]
I pinged the F-Droid guys on IRC. App page says "build failed", but logs says "build suceeded" O_o

https://f-droid.org/wiki/page/org.sufficientlysecure.ical

**Comment by tasn** [comment]
Looks good now according to the wiki.

**Comment by doak** [comment]
Confirmed, just got the F-Droid update: it works.

Thanks all lot!

Regards,
doak
