### ISSUE TITLE
URL problem ?

### ISSUE THREAD

**Issue by Montagnard65** [SufficientlySecure/calendar-import-export#51]
Hello,
I would like to use your app to import my Google Calendar with the "import URL" button. I try many URL (like https://calendar.google.com/calendar) but I always get this pop-up after using the "load" button : 
Error: Error at line 1 : Expected [-3] read [10]
I'm not sure which URL is the right one, and I can't find any forum or wiki to solve this problem...

Could you help me ?

Thanks.

**Comment by jgriffiths** [comment]
From https://support.google.com/calendar/answer/37648?hl=en:

- On a computer, open Google Calendar.
- In the top right, click Settings settings gear button > Settings.
- Open the Calendars tab.
- Click the name of the calendar you want to use.
- In the Private Address section, click ICAL.
- Copy the ICAL link that appears in the window, or click the ICAL link to download an ICS file.

**Comment by Montagnard65** [comment]
Hi jgriffiths,
Thank you for your answer and the tips. It's fully fonctionnal for my personnal account, but for the account of my company it's not working... I have only this URL (and not the private URL) :
https://calendar.google.com/calendar/ical/XXXXX%40XXXXXXXX/public/basic.ics
Is there a way to import with a automatic operation?

**Comment by jgriffiths** [comment]
@Montagnard65 Without seeing the content of the link, I think you will have to save the .ics file or email it to yourself , then click the email attachment or choose the saved .ics file to import from within the app.

**Comment by Montagnard65** [comment]
Hi @jgriffiths,
I understand where is the problem, my boss has to do this, to unblock the private URL access :
http://www.groovypost.com/howto/enable-google-apps-calendar-external-sharing-ical-private/
So now, it works well. Maybe a wiki could help someone else ?

By the way, I've two Gmail account to sync, is there a way to save the credentials for the two accounts ? Because, now, it seems the save keep only the last credentials...

**Comment by jgriffiths** [comment]
@Montagnard65 glad you got it working. Better documentation would help I'm sure, but time is limited unfortunately.

Currently you will need to enter the credentials each time I'm afraid. It would be nice to allow sync 'jobs' to be saved and also scheduled to run automatically, but unless someone steps in to implement these features they will be a while coming.

Since your use cases work, despite being non-optimal, I'm going to close this bug. Feel free to use the mailing list for suggestions/questions.
