### ISSUE TITLE
new post-2.3 release?

### ISSUE THREAD

**Issue by guillaume-d** [SufficientlySecure/calendar-import-export#52]
Could we get a new release? Or at least a new v2.4RC1 tag or similar so that we could test over F-Droid (IIUC how F-Droid works)?
(I am mostly interested in the fix for #43, I have not been able to start the app yet.)

Many thanks in advance!

**Comment by guillaume-d** [comment]
BTW the Changelog does not mention #43 being fixed.

**Comment by dschuermann** [comment]
done
