### ISSUE TITLE
Proposal Calender Backend instead of import/export.

### ISSUE THREAD

**Issue by Sur3** [SufficientlySecure/calendar-import-export#67]
Hi i wonder if it would be possible to have an .isc calender Backend. Currently there is a local calender backend and this google data kraken online backend, but if we had an .ics backend the calender events would be automatically stored to and loaded from .ics files and no manual import/export would be needed?!

**Comment by dschuermann** [comment]
Use https://icsdroid.bitfire.at/

**Comment by Sur3** [comment]
Thanks that helps me with getting rid of imports at least; though a calender using .ics as backend would still be nice to get rid of exports too, but i understand if such a backend is out of scope regarding this software here. ^^

**Comment by dschuermann** [comment]
I think ICS is then not the best format. Consider using ownCloud/nextCloud with DAVDroid for this.
