### ISSUE TITLE
Ics from email

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/calendar-import-export#8]
Open stream directly

**Comment by dschuermann** [comment]
There are other apps already doing that:
https://f-droid.org/repository/browse/?fdfilter=ics&fdid=org.dgtale.icsimport
https://f-droid.org/repository/browse/?fdfilter=ics&fdid=de.k3b.android.calendar.ics.adapter
(they both don't recommend importing large ics files)

Still, it would be nice to integrate this here

**Comment by freddupont** [comment]
It was a bug on my opinion it's corrected in the fork i'have done
