### ISSUE TITLE
Crash when exporting a local calendar

### ISSUE THREAD

**Issue by twisteros** [SufficientlySecure/calendar-import-export#95]
It happened in the latest version from f-droid (2.7.1). The previous version (2.7) also crashed.
The version 2.6 has correctly exported the same calendar.
Tested on Android 11.

Here is the screenshot from 2.7.1: 

![image](https://user-images.githubusercontent.com/18228956/161841945-787b46e6-8858-477a-b76a-7c1b5fbf138e.png)

**Comment by gargamel17** [comment]
Same problem with versions 2.70 And 2.71

**Comment by gargamel17** [comment]
Same problem in version 2.7.2

**Comment by axelsimon** [comment]
I ran into a similar problem, except that the app just crashes without any warning when "exporting".

If you install the app from Aurora Store (Google Play) instead of F-Droid, you get version 2.6 and that one works.
F-Droid currently only has 2.7.x versions available…

**Comment by fhaftmann** [comment]
> I ran into a similar problem, except that the app just crashes without any warning when "exporting".

This issue seems to be actually the one reported in https://github.com/SufficientlySecure/calendar-import-export/issues/94

**Comment by fhaftmann** [comment]
I cannot reproduce the original EPERM issue (using Android Studio’s emulator with Android 11 / API level 30 on x86_64).

**Comment by twisteros** [comment]
Version 2.7.2 crashes straight away after clicking the export button. No pop-up as it was with v2.7.1.

**Comment by twisteros** [comment]
> I cannot reproduce the original EPERM issue (using Android Studio’s emulator with Android 11 / API level 30 on x86_64).

**Comment by twisteros** [comment]
The latest version exports my calendar with no issues. Closing the ticket.

**Comment by axelsimon** [comment]
By "the latest version", Twisteros seems to mean [2.7.4](https://github.com/SufficientlySecure/calendar-import-export/releases/tag/v2.7.4).

**Comment by twisteros** [comment]
That's correct

> By "the latest version", Twisteros seems to mean [2.7.4](https://github.com/SufficientlySecure/calendar-import-export/releases/tag/v2.7.4).

**Comment by gargamel17** [comment]
2.74 works perfectly, thanks
